-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "AuditAction" ADD VALUE 'AUTH_LOGIN';
ALTER TYPE "AuditAction" ADD VALUE 'AUTH_LOGOUT';
ALTER TYPE "AuditAction" ADD VALUE 'AUTH_FAILED_LOGIN';
ALTER TYPE "AuditAction" ADD VALUE 'MEMBERSHIP_INVITE_SENT';
ALTER TYPE "AuditAction" ADD VALUE 'MEMBERSHIP_ROLE_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'BUILDING_CREATE';
ALTER TYPE "AuditAction" ADD VALUE 'BUILDING_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE 'BUILDING_DELETE';
ALTER TYPE "AuditAction" ADD VALUE 'UNIT_CREATE';
ALTER TYPE "AuditAction" ADD VALUE 'UNIT_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE 'UNIT_DELETE';
ALTER TYPE "AuditAction" ADD VALUE 'OCCUPANT_ASSIGN';
ALTER TYPE "AuditAction" ADD VALUE 'OCCUPANT_REMOVE';
ALTER TYPE "AuditAction" ADD VALUE 'TICKET_CREATE';
ALTER TYPE "AuditAction" ADD VALUE 'TICKET_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE 'TICKET_STATUS_CHANGE';
ALTER TYPE "AuditAction" ADD VALUE 'TICKET_ASSIGN';
ALTER TYPE "AuditAction" ADD VALUE 'TICKET_COMMENT_ADD';
ALTER TYPE "AuditAction" ADD VALUE 'TICKET_DELETE';
ALTER TYPE "AuditAction" ADD VALUE 'COMMUNICATION_CREATE_DRAFT';
ALTER TYPE "AuditAction" ADD VALUE 'COMMUNICATION_EDIT_DRAFT';
ALTER TYPE "AuditAction" ADD VALUE 'COMMUNICATION_SEND';
ALTER TYPE "AuditAction" ADD VALUE 'COMMUNICATION_READ';
ALTER TYPE "AuditAction" ADD VALUE 'FILE_UPLOADED';
ALTER TYPE "AuditAction" ADD VALUE 'DOCUMENT_CREATE';
ALTER TYPE "AuditAction" ADD VALUE 'DOCUMENT_VISIBILITY_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'DOCUMENT_DOWNLOADED';
ALTER TYPE "AuditAction" ADD VALUE 'DOCUMENT_DELETE';
ALTER TYPE "AuditAction" ADD VALUE 'CHARGE_CREATE';
ALTER TYPE "AuditAction" ADD VALUE 'CHARGE_CANCEL';
ALTER TYPE "AuditAction" ADD VALUE 'PAYMENT_SUBMIT';
ALTER TYPE "AuditAction" ADD VALUE 'PAYMENT_APPROVE';
ALTER TYPE "AuditAction" ADD VALUE 'PAYMENT_REJECT';
ALTER TYPE "AuditAction" ADD VALUE 'PAYMENT_ALLOCATE';
ALTER TYPE "AuditAction" ADD VALUE 'ALLOCATION_DELETE';
ALTER TYPE "AuditAction" ADD VALUE 'VENDOR_CREATE';
ALTER TYPE "AuditAction" ADD VALUE 'VENDOR_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE 'VENDOR_DELETE';
ALTER TYPE "AuditAction" ADD VALUE 'VENDOR_ASSIGN';
ALTER TYPE "AuditAction" ADD VALUE 'VENDOR_UNASSIGN';
ALTER TYPE "AuditAction" ADD VALUE 'QUOTE_CREATE';
ALTER TYPE "AuditAction" ADD VALUE 'QUOTE_STATUS_CHANGE';
ALTER TYPE "AuditAction" ADD VALUE 'WORK_ORDER_CREATE';
ALTER TYPE "AuditAction" ADD VALUE 'WORK_ORDER_STATUS_CHANGE';

-- AlterTable
ALTER TABLE "AuditLog" ADD COLUMN     "actorMembershipId" TEXT;

-- CreateIndex
CREATE INDEX "AuditLog_entity_idx" ON "AuditLog"("entity");
