import { DocumentVisibility } from '@prisma/client';

/**
 * File response DTO - safe subset of File entity
 */
export class FileResponseDto {
  id!: string;
  tenantId!: string;
  bucket!: string;
  objectKey!: string;
  originalName!: string;
  mimeType!: string;
  size!: number;
  checksum!: string;
  createdByMembershipId!: string;
  createdAt!: Date;
}

/**
 * User response DTO - safe subset for display
 */
export class UserResponseDto {
  id!: string;
  fullName!: string;
  email!: string;
  phone?: string;
}

/**
 * Membership response DTO - user + role context
 */
export class MembershipResponseDto {
  id!: string;
  userId!: string;
  user?: UserResponseDto;
}

/**
 * Financial payment metadata attached to a document when the document
 * is linked to a Payment record via:
 *   - Payment.receiptDocumentId === Document.id  (receipt)
 *   - Payment.proofFileId === Document.fileId    (proof)
 */
export class DocumentPaymentMetadataDto {
  id!: string;
  /** Amount in cents */
  amount!: number;
  currency!: string;
  status!: string;
  reference?: string | null;
  receiptNumber?: string | null;
  /**
   * Period resolved from the first PaymentAllocation.charge.expensePeriod.
   * null when: no allocations, multiple distinct periods, or no unambiguous period.
   * Format: "YYYY-MM" when present.
   */
  period?: string | null;
}

/**
 * Document response DTO - main response for list/get/create/update
 */
export class DocumentResponseDto {
  id!: string;
  tenantId!: string;
  fileId!: string;
  title!: string;
  category!: string;
  visibility!: DocumentVisibility;
  buildingId?: string;
  unitId?: string;
  createdByMembershipId!: string;
  createdByMembership?: MembershipResponseDto;
  createdAt!: Date;
  updatedAt!: Date;

  /**
   * Functional classification based on real Payment relationships.
   * - PAYMENT_PROOF: Payment.proofFileId === Document.fileId
   * - PAYMENT_RECEIPT: Payment.receiptDocumentId === Document.id
   * - null: not linked to any payment
   *
   * Never derived from title parsing, category, or heuristics.
   */
  functionalType?: 'PAYMENT_PROOF' | 'PAYMENT_RECEIPT' | null;
  /**
   * Origin of the document content.
   * - UPLOADED: file was uploaded by a user (resident or admin)
   * - GENERATED: file was generated by BuildingOS (e.g. receipt PDF)
   * - null: not linked to any payment
   */
  origin?: 'UPLOADED' | 'GENERATED' | null;
  /**
   * Financial payment metadata when the document is linked to a Payment.
   * null when not linked.
   */
  payment?: DocumentPaymentMetadataDto | null;
}

/**
 * Document with file response DTO - includes file details
 */
export class DocumentWithFileResponseDto extends DocumentResponseDto {
  file?: FileResponseDto;
}

/**
 * Download URL response DTO
 */
export class DownloadUrlResponseDto {
  url!: string;
  expiresAt!: Date;
}
