import { Transform, Type } from 'class-transformer';
import {
  IsDate,
  IsIn,
  IsInt,
  IsOptional,
  IsString,
  Max,
  MaxLength,
  Min,
} from 'class-validator';

const trimString = ({ value }: { value: unknown }): unknown =>
  typeof value === 'string' ? value.trim() : value;

export const TENANT_AUDIT_ACTION_VALUES = [
  'TENANT_CREATE',
  'TENANT_UPDATE',
  'TENANT_DELETE',
  'TENANT_BRANDING_UPDATED',
  'SUBSCRIPTION_CREATE',
  'SUBSCRIPTION_UPDATE',
  'SUBSCRIPTION_CANCEL',
  'SUBSCRIPTION_PAST_DUE',
  'USER_CREATE',
  'USER_DELETE',
  'OTHER',
  'AUTH_LOGIN',
  'AUTH_LOGOUT',
  'AUTH_FAILED_LOGIN',
  'MEMBERSHIP_INVITE_SENT',
  'MEMBERSHIP_INVITE_ACCEPTED',
  'MEMBERSHIP_INVITE_REVOKED',
  'MEMBERSHIP_INVITE_RESENT',
  'MEMBERSHIP_INVITE_EXPIRED',
  'MEMBERSHIP_ROLE_CHANGED',
  'ROLE_ASSIGNED',
  'ROLE_REMOVED',
  'IMPERSONATION_START',
  'IMPERSONATION_END',
  'BUILDING_CREATE',
  'BUILDING_UPDATE',
  'BUILDING_DELETE',
  'UNIT_CREATE',
  'UNIT_UPDATE',
  'UNIT_DELETE',
  'OCCUPANT_ASSIGN',
  'OCCUPANT_REMOVE',
  'TENANT_MEMBER_CREATE',
  'TENANT_MEMBER_UPDATE',
  'TENANT_MEMBER_INVITED',
  'TENANT_MEMBER_DELETE',
  'TICKET_CREATE',
  'TICKET_UPDATE',
  'TICKET_STATUS_CHANGE',
  'TICKET_ASSIGN',
  'TICKET_COMMENT_ADD',
  'TICKET_DELETE',
  'TICKET_ESCALATED',
  'COMMUNICATION_CREATE_DRAFT',
  'COMMUNICATION_EDIT_DRAFT',
  'COMMUNICATION_SEND',
  'COMMUNICATION_READ',
  'FILE_UPLOADED',
  'DOCUMENT_CREATE',
  'DOCUMENT_VISIBILITY_CHANGED',
  'DOCUMENT_DOWNLOADED',
  'DOCUMENT_DELETE',
  'IMPORT_FILE_LOADED',
  'IMPORT_PREVIEW_READY',
  'IMPORT_PREVIEW_BLOCKED',
  'IMPORT_PREVIEW_FAILED',
  'IMPORT_CONFIRM_STARTED',
  'IMPORT_CONFIRMED',
  'IMPORT_CONFIRM_FAILED',
  'IMPORT_RECONFIRM_ATTEMPT',
  'CHARGE_CREATE',
  'CHARGE_CANCEL',
  'PAYMENT_SUBMIT',
  'PAYMENT_APPROVE',
  'PAYMENT_REJECT',
  'PAYMENT_CANCEL',
  'PAYMENT_ALLOCATE',
  'ALLOCATION_DELETE',
  'VENDOR_CREATE',
  'VENDOR_UPDATE',
  'VENDOR_DELETE',
  'VENDOR_ASSIGN',
  'VENDOR_UNASSIGN',
  'QUOTE_CREATE',
  'QUOTE_STATUS_CHANGE',
  'WORK_ORDER_CREATE',
  'WORK_ORDER_STATUS_CHANGE',
  'SUPPORT_TICKET_CREATE',
  'SUPPORT_TICKET_UPDATE',
  'SUPPORT_TICKET_STATUS_CHANGE',
  'SUPPORT_TICKET_ASSIGN',
  'SUPPORT_TICKET_COMMENT_ADD',
  'SUPPORT_TICKET_CLOSE',
  'NOTIFICATION_CREATED',
  'NOTIFICATION_READ',
  'NOTIFICATION_DELETED',
  'DEMO_SEED_CREATED',
  'REPORT_EXPORTED',
  'AI_INTERACTION',
  'AI_TEMPLATE_RUN',
  'AI_BUDGET_WARNED',
  'AI_BUDGET_BLOCKED',
  'AI_BUDGET_UPDATED',
  'AI_DEGRADED_BUDGET',
  'AI_ACTION_CLICKED',
  'AI_LIMIT_WARNED',
  'AI_LIMIT_BLOCKED',
  'AI_TENANT_OVERRIDE_UPDATED',
  'AI_PLAN_CAPS_CHANGED',
  'PLAN_CHANGE_REQUESTED',
  'PLAN_CHANGE_REQUEST_CANCELED',
  'PLAN_CHANGE_APPROVED',
  'PLAN_CHANGE_REJECTED',
  'LEAD_CREATED',
  'LEAD_STATUS_CHANGED',
  'LEAD_DELETED',
  'LEAD_CONVERTED',
  'UNIT_CATEGORY_CREATE',
  'UNIT_CATEGORY_UPDATE',
  'UNIT_CATEGORY_DELETE',
  'UNIT_CATEGORY_AUTO_ASSIGN',
  'EXPENSE_PERIOD_CREATE',
  'EXPENSE_PERIOD_GENERATE',
  'EXPENSE_PERIOD_PUBLISH',
  'EXPENSE_PERIOD_DELETE',
  'EXPENSE_CREATE',
  'EXPENSE_VALIDATE',
  'EXPENSE_VOID',
  'EXPENSE_UPDATE',
  'EXPENSE_IMPORTED',
  'EXPENSE_LEDGER_CATEGORY_CREATE',
  'EXPENSE_LEDGER_CATEGORY_UPDATE',
  'EXPENSE_LEDGER_CATEGORY_DELETE',
  'LIQUIDATION_DRAFT',
  'LIQUIDATION_REVIEW',
  'LIQUIDATION_PUBLISH',
  'LIQUIDATION_CANCEL',
  'INCOME_CREATE',
  'INCOME_UPDATE',
  'INCOME_RECORD',
  'INCOME_VOID',
  'INCOME_ALLOCATION_CREATE',
  'UNIT_GROUP_CREATE',
  'UNIT_GROUP_DELETE',
  'UNIT_GROUP_MEMBER_ADD',
  'UNIT_GROUP_MEMBER_REMOVE',
  'EXPENSE_ALLOCATION_CREATE',
] as const;

export type TenantAuditAction = (typeof TENANT_AUDIT_ACTION_VALUES)[number];

export class TenantAuditLogQueryDto {
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(0)
  skip?: number = 0;

  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  @Max(100)
  take?: number = 10;

  @IsOptional()
  @Transform(trimString)
  @IsIn(TENANT_AUDIT_ACTION_VALUES)
  action?: TenantAuditAction;

  @IsOptional()
  @Transform(trimString)
  @Type(() => Date)
  @IsDate()
  dateFrom?: Date;

  @IsOptional()
  @Transform(trimString)
  @Type(() => Date)
  @IsDate()
  dateTo?: Date;
}
